import hamburguer from '../assets/category-hamburguer.png';

export const Products = [
  {
    id: 1,
    image: hamburguer,
    title: 'Smash da casa',
    description: '2x hambúrguer 200g',
    price: 30.5,
  },
  {
    id: 2,
    image: hamburguer,
    title: 'Maclaren',
    description: 'hambúrguer 200g',
    price: 22,
  },
  {
    id: 3,
    image: hamburguer,
    title: 'Guincho',
    description: '3x hambúrguer 200g',
    price: 26.5,
  },
  {
    id: 4,
    image: hamburguer,
    title: 'Brasil',
    description: '2x hambúrguer 200g',
    price: 24,
  },
  {
    id: 5,
    image: hamburguer,
    title: 'Yoda',
    description: '2x hambúrguer 200g',
    price: 22.5,
  },
  {
    id: 6,
    image: hamburguer,
    title: 'King Kong',
    description: '2x hambúrguer 200g',
    price: 38,
  },
  {
    id: 7,
    image: hamburguer,
    title: 'X-Tudo',
    description: '2x hambúrguer 200g',
    price: 34,
  },
  {
    id: 8,
    image: hamburguer,
    title: 'Whooper',
    description: '2x hambúrguer 200g',
    price: 26,
  },
  {
    id: 9,
    image: hamburguer,
    title: 'Bauru',
    description: '2x hambúrguer 200g',
    price: 31,
  },
  {
    id: 10,
    image: hamburguer,
    title: 'Burguer Mania',
    description: '2x hambúrguer 200g',
    price: 30.5,
  },
  {
    id: 11,
    image: hamburguer,
    title: 'Estados Unidos',
    description: '2x hambúrguer 200g',
    price: 15.5,
  },
  {
    id: 12,
    image: hamburguer,
    title: 'Chile',
    description: '2x hambúrguer 200g',
    price: 14,
  },
];
