import hamburguer from '../assets/category-hamburguer.png';

export const Products = [
  {
    id: 1,
    image: hamburguer,
    title: 'Smash da casa',
    description: '2x hambúrguer 200g',
    price: 30.5,
  },
  {
    id: 2,
    image: hamburguer,
    title: 'Smash da casa',
    description: '2x hambúrguer 200g',
    price: 35.5,
  },
  {
    id: 3,
    image: hamburguer,
    title: 'Smash da casa',
    description: '2x hambúrguer 200g',
    price: 30.5,
  },
  {
    id: 4,
    image: hamburguer,
    title: 'Smash da casa',
    description: '2x hambúrguer 200g',
    price: 30.5,
  },
  {
    id: 5,
    image: hamburguer,
    title: 'Smash da casa',
    description: '2x hambúrguer 200g',
    price: 30.5,
  },
  {
    id: 6,
    image: hamburguer,
    title: 'Smash da casa',
    description: '2x hambúrguer 200g',
    price: 30.5,
  },
  {
    id: 7,
    image: hamburguer,
    title: 'Smash da casa',
    description: '2x hambúrguer 200g',
    price: 30.5,
  },
  {
    id: 8,
    image: hamburguer,
    title: 'Smash da casa',
    description: '2x hambúrguer 200g',
    price: 30.5,
  },
  {
    id: 9,
    image: hamburguer,
    title: 'Smash da casa',
    description: '2x hambúrguer 200g',
    price: 30.5,
  },
  {
    id: 10,
    image: hamburguer,
    title: 'Smash da casa',
    description: '2x hambúrguer 200g',
    price: 30.5,
  },
  {
    id: 11,
    image: hamburguer,
    title: 'Smash da casa',
    description: '2x hambúrguer 200g',
    price: 30.5,
  },
  {
    id: 12,
    image: hamburguer,
    title: 'Smash da casa',
    description: '2x hambúrguer 200g',
    price: 30.5,
  },
];
